version: '3.7'
services:
  mysql:
    image: martaniblett/energise_app_mysql:latest
    ports:
      - target: 3306
        published: 3306
    env_file:
     - ./db.env
  service1:
    image: martaniblett/energise_app_service1:latest
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
    depends_on:
      - mysql
  service2:
    image: martaniblett/energise_app_service2:latest
    ports:
      - target: 5001
        published: 5001
        protocol: tcp
  service3:
    image: martaniblett/energise_app_service3:latest
    ports:
      - target: 5002
        published: 5002
        protocol: tcp
  service4:
    image: martaniblett/energise_app_service4:latest
    ports:
      - target: 5003
        published: 5003
        protocol: tcp
